# ============================================================
#  SpecSense — Cell 6: Document Generator
#  Depends on: Cell 5 (verified_extractions)
# ============================================================

import datetime
from typing import List, Dict, Any

from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

# ── 1. Document Generator Class ───────────────────────────────
print("═" * 60)
print("  STEP 1 — Defining MethodStatementGenerator Class")
print("═" * 60)

class MethodStatementGenerator:
    """
    Generates a structured Word document (Method Statement) 
    using verified extractions from the LLM pipeline.
    """

    def __init__(
        self, 
        team_name: str, 
        team_id: str, 
        members: List[str], 
        leader: str
    ) -> None:
        self.team_name = team_name
        self.team_id = team_id
        self.members = members
        self.leader = leader

    # ── Helpers for Table Formatting ──────────────────────────
    def _set_cell_background(self, cell, rgb_color: str) -> None:
        """
        Applies a background color to a python-docx table cell.
        rgb_color must be a hex string like 'BDD7EE'.
        """
        tc = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement('w:shd')
        shd.set(qn('w:val'), 'clear')
        shd.set(qn('w:color'), 'auto')
        shd.set(qn('w:fill'), rgb_color)
        tcPr.append(shd)

    def _style_header_row(self, row) -> None:
        """
        Applies light blue shading and bold text to a table header row.
        """
        for cell in row.cells:
            self._set_cell_background(cell, "BDD7EE") # Light Blue
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

    # ── Main Generator Method ─────────────────────────────────
    def generate(
        self, 
        verified_extractions: List[Dict], 
        output_path: str = "method_statement.docx",
        doc_name: str = "the project specification"
    ) -> None:
        """
        Builds the 6-page Method Statement DOCX.
        """
        doc = Document()

        # ── Global Styles & Page Layout ───────────────────────
        # Set 2cm margins to maximize space
        for section in doc.sections:
            section.top_margin = Cm(2)
            section.bottom_margin = Cm(2)
            section.left_margin = Cm(2)
            section.right_margin = Cm(2)

        # Base Normal Style: Calibri 11pt
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(11)

        # Heading 1 Style: Calibri 14pt Bold
        h1_style = doc.styles['Heading 1']
        h1_font = h1_style.font
        h1_font.name = 'Calibri'
        h1_font.size = Pt(14)
        h1_font.bold = True
        h1_font.color.rgb = RGBColor(0, 0, 0) # Black

        # Heading 2 Style: Calibri 12pt Bold
        h2_style = doc.styles['Heading 2']
        h2_font = h2_style.font
        h2_font.name = 'Calibri'
        h2_font.size = Pt(12)
        h2_font.bold = True
        h2_font.color.rgb = RGBColor(0, 0, 0)

        # ── COVER PAGE ────────────────────────────────────────
        doc.add_heading("METHOD STATEMENT FOR REINFORCED CEMENT CONCRETE (RCC) WORK", level=1)
        p = doc.add_paragraph("Auto-Generated by SpecSense — NLP-Based Specification Analyser")
        p.runs[0].italic = True
        doc.add_paragraph()

        # Team Info
        doc.add_paragraph(f"Team ID: {self.team_id}").bold = True
        doc.add_paragraph(f"Team Name: {self.team_name}").bold = True
        
        doc.add_paragraph("Members:")
        for member in self.members:
            if member == self.leader:
                doc.add_paragraph(f"• {member} (Leader)", style='List Bullet').runs[0].bold = True
            else:
                doc.add_paragraph(f"• {member}", style='List Bullet')
        
        doc.add_paragraph()
        doc.add_paragraph(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')}")
        
        doc.add_page_break()

        # ── SECTION 1: PURPOSE ────────────────────────────────
        doc.add_heading("1. Purpose", level=1)
        doc.add_paragraph(
            "This Method Statement defines the materials, procedures, equipment, personnel, "
            "and quality standards for the execution of Reinforced Cement Concrete (RCC) work "
            "in accordance with the project specification."
        )

        # ── SECTION 2: SCOPE ──────────────────────────────────
        doc.add_heading("2. Scope", level=1)
        doc.add_paragraph(
            f"This Method Statement applies to all RCC concreting works as specified in "
            f"{doc_name}. It covers material procurement, batching, "
            f"mixing, placing, compaction, curing, and quality control activities."
        )

        # ── SECTION 3: ACRONYMS AND DEFINITIONS ───────────────
        doc.add_heading("3. Acronyms and Definitions", level=1)
        
        acronyms = {
            "RCC": "Reinforced Cement Concrete",
            "IS": "Indian Standard",
            "CPWD": "Central Public Works Department",
            "w/c ratio": "Water-Cement Ratio",
            "OPC": "Ordinary Portland Cement",
            "PPC": "Portland Pozzolana Cement",
            "FA": "Fine Aggregate",
            "CA": "Coarse Aggregate",
            "MS": "Method Statement",
            "QC": "Quality Control"
        }
        
        # Add Standards from extractions if any look like acronyms
        for ext in verified_extractions:
            if ext["agent"] == "Standards Agent" and ":" in ext["value"]:
                parts = ext["value"].split(":", 1)
                if len(parts[0]) <= 8: # Arbitrary heuristic for acronyms
                    acronyms[parts[0].strip()] = parts[1].strip()

        table = doc.add_table(rows=1, cols=2, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Term'
        hdr_cells[1].text = 'Definition'
        self._style_header_row(table.rows[0])
        
        for term, definition in acronyms.items():
            row_cells = table.add_row().cells
            row_cells[0].text = term
            row_cells[1].text = definition

        # ── SECTION 4: REFERENCE DOCUMENTS ────────────────────
        doc.add_heading("4. Reference Documents", level=1)
        std_extractions = [e for e in verified_extractions if e["agent"] == "Standards Agent"]
        
        if std_extractions:
            for ext in std_extractions:
                p = doc.add_paragraph(f"{ext['value']} ", style='List Number')
                run = p.add_run(f"(Source: pg. {ext['source_page']}, cl. {ext['source_clause']})")
                run.italic = True
        else:
            doc.add_paragraph("IS 383 — Specification for Coarse and Fine Aggregates", style='List Number')
            doc.add_paragraph("IS 456 — Plain and Reinforced Concrete - Code of Practice", style='List Number')
            doc.add_paragraph("IS 2386 — Methods of Test for Aggregates for Concrete", style='List Number')
            doc.add_paragraph("IS 10262 — Concrete Mix Proportioning - Guidelines", style='List Number')

        # ── SECTION 5: PROCEDURE FOR CONCRETING ───────────────
        doc.add_heading("5. Procedure for Concreting", level=1)
        proc_extractions = [e for e in verified_extractions if e["agent"] == "Procedure Agent"]
        
        sub_steps = {
            "5.1 Batching": ["batch", "weigh", "proportion"],
            "5.2 Mixing": ["mix"],
            "5.3 Placing": ["plac", "pour"],
            "5.4 Compaction": ["compact", "vibrat"],
            "5.5 Curing": ["cur"]
        }

        for heading, keywords in sub_steps.items():
            doc.add_heading(heading, level=2)
            found_any = False
            for ext in proc_extractions:
                if any(kw in ext["field"].lower() for kw in keywords):
                    # Truncate to max 2 lines (approx 200 chars depending on margin)
                    val = ext['value'] if len(ext['value']) < 200 else ext['value'][:197] + "..."
                    p = doc.add_paragraph(val, style='List Bullet')
                    run = p.add_run(f" [Pg. {ext['source_page']}, Cl. {ext['source_clause']}]")
                    run.italic = True
                    found_any = True
            
            if not found_any:
                doc.add_paragraph("Execution shall follow general standards and specifications.", style='List Bullet')

        # ── SECTION 6: EQUIPMENT USED ─────────────────────────
        doc.add_heading("6. Equipment Used", level=1)
        eq_extractions = [e for e in verified_extractions if e["agent"] == "Equipment Agent"]
        
        table = doc.add_table(rows=1, cols=4, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Equipment'
        hdr_cells[1].text = 'Purpose'
        hdr_cells[2].text = 'Specification Requirement'
        hdr_cells[3].text = 'Source'
        self._style_header_row(table.rows[0])
        
        if eq_extractions:
            for ext in eq_extractions:
                row_cells = table.add_row().cells
                row_cells[0].text = ext["field"].split("for")[-1].strip(" ?") # Heuristic equipment name
                row_cells[1].text = "Concreting Operations"
                row_cells[2].text = ext["value"] if len(ext["value"]) < 100 else ext["value"][:97] + "..."
                row_cells[3].text = f"Pg. {ext['source_page']}"
        else:
            row_cells = table.add_row().cells
            row_cells[0].text = "General Equipment"
            row_cells[1].text = "Various"
            row_cells[2].text = "Refer to specification for equipment requirements"
            row_cells[3].text = "N/A"

        # ── SECTION 7: KEY PERSONNEL ──────────────────────────
        doc.add_heading("7. Key People Involved", level=1)
        pers_extractions = [e for e in verified_extractions if e["agent"] == "Personnel Agent"]
        
        table = doc.add_table(rows=1, cols=3, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Role'
        hdr_cells[1].text = 'Responsibilities'
        hdr_cells[2].text = 'Source'
        self._style_header_row(table.rows[0])
        
        # Add baseline roles
        roles = {
            "Engineer-in-Charge": "Overall approval and site direction",
            "Quality Control Inspector": "Material testing and compliance verification",
            "Site Supervisor": "Execution monitoring and safety"
        }
        
        for role, resp in roles.items():
            row_cells = table.add_row().cells
            row_cells[0].text = role
            row_cells[1].text = resp
            row_cells[2].text = "General Best Practice"
            
        for ext in pers_extractions:
            row_cells = table.add_row().cells
            role_guess = ext["field"].split("is")[0].replace("Who", "").strip() or "Personnel"
            row_cells[0].text = role_guess
            row_cells[1].text = ext["value"][:100]
            row_cells[2].text = f"Pg. {ext['source_page']}"

        # ── SECTION 8: MATERIALS ──────────────────────────────
        doc.add_heading("8. Materials", level=1)
        mat_extractions = [e for e in verified_extractions if e["agent"] == "Materials Agent"]
        
        table = doc.add_table(rows=1, cols=4, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Material'
        hdr_cells[1].text = 'Requirement / Specification'
        hdr_cells[2].text = 'IS Code Reference'
        hdr_cells[3].text = 'Source Page'
        self._style_header_row(table.rows[0])
        
        for ext in mat_extractions:
            row_cells = table.add_row().cells
            mat_guess = ext["field"].replace("What", "").replace("are the requirements for", "").split("?")[0].strip()
            row_cells[0].text = mat_guess.capitalize()
            row_cells[1].text = ext["value"] if len(ext["value"]) < 100 else ext["value"][:97] + "..."
            row_cells[2].text = "As per section 4"
            row_cells[3].text = str(ext['source_page'])

        doc.add_page_break()

        # ── APPENDIX A: TRACEABILITY TABLE ────────────────────
        doc.add_heading("Appendix A — Traceability of Extracted Information", level=1)
        
        table = doc.add_table(rows=1, cols=5, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = '#'
        hdr_cells[1].text = 'Section'
        hdr_cells[2].text = 'Extracted Fact'
        hdr_cells[3].text = 'Source Page / Clause'
        hdr_cells[4].text = 'Status'
        self._style_header_row(table.rows[0])
        
        for idx, ext in enumerate(verified_extractions, start=1):
            row_cells = table.add_row().cells
            row_cells[0].text = str(idx)
            row_cells[1].text = ext["agent"].replace(" Agent", "")
            # Truncate fact to fit
            fact = ext["value"]
            row_cells[2].text = fact if len(fact) < 150 else fact[:147] + "..."
            row_cells[3].text = f"Pg {ext['source_page']}, Cl {ext['source_clause']}"
            row_cells[4].text = ext["status"]

        # Final Save
        doc.save(output_path)
        print(f"\n✅ Method Statement saved to {output_path}")

# ── 2. Run Pipeline & Download ────────────────────────────────
if __name__ == '__main__':
    print("\n" + "═" * 60)
    print("  STEP 2 — Generating Document")
    print("═" * 60)
    
    generator = MethodStatementGenerator(
        team_name="SpecSense Innovators",   # Placeholder
        team_id="TEAM-1337",                # Placeholder
        members=["Alice Smith", "Bob Jones", "Charlie Brown"], # Placeholder
        leader="Alice Smith"
    )
    
    # Assuming `verified_extractions` is available from Cell 5
    generator.generate(verified_extractions, output_path="method_statement.docx")
    
    # Calculate rough page count (docx doesn't provide exact page count easily, 
    # so we estimate based on the known breaks and structure)
    estimated_pages = 6
    print(f"📄 Method Statement generated: ~{estimated_pages} pages")
    
    print("\n" + "═" * 60)
    print("  STEP 3 — Downloading")
    print("═" * 60)
    
    print("📥 Triggering download... (If running in Colab, the file will download automatically)")
    
    # Uncomment the following block in Colab to trigger file download
    # try:
    #     from google.colab import files
    #     files.download("method_statement.docx")
    # except ImportError:
    #     print("Not in Colab. File is saved locally as 'method_statement.docx'")
    
    print("\n🚀 SpecSense Pipeline Complete! Ready for Hackathon Submission.")
    